from django.urls import path

from .views import (
    my_notifications_view,
    generate_my_notifications_view,
    mark_notification_read_view,
    mark_all_notifications_read_view,
    admin_notifications_view,
    generate_camp_proximity_alerts_view,
    generate_blood_demand_alerts_view,
    blood_demand_alerts_list_view,
    campaign_blast_view,
    admin_sms_settings_view,
    admin_sms_toggle_view,
    admin_sms_test_view,
    admin_sms_logs_view,
    admin_sms_bulk_view,
    admin_whatsapp_settings_view,
    admin_whatsapp_toggle_view,
    admin_whatsapp_test_view,
    admin_whatsapp_logs_view,
    admin_whatsapp_bulk_view,
    donor_whatsapp_consent_view,
)


urlpatterns = [
    path("my/", my_notifications_view),
    path("generate-my/", generate_my_notifications_view),
    path("<int:notification_id>/read/", mark_notification_read_view),
    path("read-all/", mark_all_notifications_read_view),
    path("admin/", admin_notifications_view),
    path("admin/camp-proximity-alerts/", generate_camp_proximity_alerts_view),
    path("admin/blood-demand-alerts/", generate_blood_demand_alerts_view),
    path("admin/blood-demand-alerts/list/", blood_demand_alerts_list_view),
    path("admin/campaign-blast/", campaign_blast_view),
    path("admin/sms/settings/", admin_sms_settings_view),
    path("admin/sms/toggle/", admin_sms_toggle_view),
    path("admin/sms/test/", admin_sms_test_view),
    path("admin/sms/logs/", admin_sms_logs_view),
    path("admin/sms/bulk/", admin_sms_bulk_view),
    path("admin/whatsapp/settings/", admin_whatsapp_settings_view),
    path("admin/whatsapp/toggle/", admin_whatsapp_toggle_view),
    path("admin/whatsapp/test/", admin_whatsapp_test_view),
    path("admin/whatsapp/logs/", admin_whatsapp_logs_view),
    path("admin/whatsapp/bulk/", admin_whatsapp_bulk_view),
    path("whatsapp/consent/", donor_whatsapp_consent_view),
]