# Generated by Django 6.0.5 on 2026-06-15 16:01

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Notification',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=150)),
                ('message', models.TextField()),
                ('notification_type', models.CharField(choices=[('RETENTION', 'Retention Reminder'), ('BADGE', 'Badge Earned'), ('CAMP', 'Nearby Camp'), ('BLOOD_DEMAND', 'Blood Demand'), ('SYSTEM', 'System')], default='SYSTEM', max_length=30)),
                ('target_role', models.CharField(choices=[('DONOR', 'Donor'), ('ADMIN', 'Admin'), ('BOTH', 'Both')], default='DONOR', max_length=20)),
                ('is_read', models.BooleanField(default=False)),
                ('action_label', models.CharField(blank=True, max_length=100)),
                ('action_url', models.CharField(blank=True, max_length=255)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('recipient', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='notifications', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
    ]
