# Generated by Django 5.2.5 on 2026-06-18 20:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('notifications', '0004_whatsapplog_whatsappsetting'),
    ]

    operations = [
        migrations.AddField(
            model_name='blooddemandalert',
            name='hospital_name',
            field=models.CharField(blank=True, max_length=200),
        ),
        migrations.AddField(
            model_name='blooddemandalert',
            name='notified_count',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='blooddemandalert',
            name='resolved_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='blooddemandalert',
            name='units_needed',
            field=models.PositiveIntegerField(default=1),
        ),
        migrations.AddField(
            model_name='blooddemandalert',
            name='urgency_level',
            field=models.CharField(choices=[('CRITICAL', 'Critical'), ('HIGH', 'High'), ('MEDIUM', 'Medium'), ('LOW', 'Low')], default='HIGH', max_length=10),
        ),
    ]
