# Generated by Django 6.0.5 on 2026-05-27 16:44

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('donors', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='EligibilityAssessment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('is_eligible', models.BooleanField()),
                ('age', models.IntegerField(blank=True, null=True)),
                ('reasons', models.JSONField(default=list)),
                ('summary', models.TextField()),
                ('assessed_at', models.DateTimeField(auto_now_add=True)),
                ('donor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='eligibility_assessments', to='donors.donorprofile')),
            ],
        ),
    ]
