# Generated by Django 6.0.5 on 2026-05-27 16:51

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('donors', '0002_eligibilityassessment'),
    ]

    operations = [
        migrations.CreateModel(
            name='AvailabilityAssessment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('is_available', models.BooleanField()),
                ('availability_probability', models.FloatField()),
                ('reasons', models.JSONField(default=list)),
                ('summary', models.TextField()),
                ('assessed_at', models.DateTimeField(auto_now_add=True)),
                ('donor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='availability_assessments', to='donors.donorprofile')),
            ],
        ),
    ]
