# Generated by Django 6.0.5 on 2026-06-09 11:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('donors', '0004_donorbadge'),
    ]

    operations = [
        migrations.AddField(
            model_name='donorprofile',
            name='total_donations',
            field=models.PositiveIntegerField(default=0),
        ),
    ]
