# Generated by Django 6.0.5 on 2026-06-21 14:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('camps', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='donationcamp',
            name='status',
            field=models.CharField(choices=[('ACTIVE', 'Active'), ('INACTIVE', 'Inactive'), ('UPCOMING', 'Upcoming'), ('COMPLETED', 'Completed')], default='ACTIVE', max_length=20),
        ),
    ]
