# Generated by Django 6.0.5 on 2026-06-16 16:58

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='CampaignPerformance',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('blood_group', models.CharField(blank=True, max_length=5, null=True)),
                ('radius_km', models.FloatField(default=10)),
                ('campaign_latitude', models.FloatField(blank=True, null=True)),
                ('campaign_longitude', models.FloatField(blank=True, null=True)),
                ('total_matches', models.PositiveIntegerField(default=0)),
                ('available_donors', models.PositiveIntegerField(default=0)),
                ('unavailable_donors', models.PositiveIntegerField(default=0)),
                ('high_priority_donors', models.PositiveIntegerField(default=0)),
                ('medium_priority_donors', models.PositiveIntegerField(default=0)),
                ('low_priority_donors', models.PositiveIntegerField(default=0)),
                ('ineligible_donors', models.PositiveIntegerField(default=0)),
                ('outside_radius_donors', models.PositiveIntegerField(default=0)),
                ('skipped_donors', models.PositiveIntegerField(default=0)),
                ('average_availability_score', models.FloatField(default=0)),
                ('average_campaign_priority_score', models.FloatField(default=0)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='campaign_performance_records', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
    ]
